apiVersion: v1
kind: Secret
metadata:
  name: focus-flow-cloud-secret
  namespace: focus-flow-cloud
type: Opaque
stringData:
  POSTGRES_USER: "<your-postgres-user>"
  POSTGRES_PASSWORD: "<your-postgres-password>"
  POSTGRES_DB: "<your-postgres-db>"
  JWT_SECRET: "<your-jwt-secret>"
  VAPID_PRIVATE_KEY: "<your-vapid-private-key>"
